### ISSUE TITLE
Anonymous ldap bind

### ISSUE THREAD

**Issue by DudeCalledBro** [oxzi/greenlight-ldap-sync#1]
First of all, we really appreciate your project. We'd love to see this feature in upstream greenlight, but this solution might also work very well! :)

We still struggle to bind ldap anonymously (greenlight ldap-authentication works fine though). Seems like greenlight-ldap-sync is not happy with a zero-length bind DN and/or a zero-length password and keeps returning `invalid DN`.

```bash
level=error msg="Cannot establish LDAP connection" error="LDAP Result Code 34 \"Invalid DN Syntax\": invalid DN"
```

Thank you :100:

**Comment by oxzi** [comment]
> First of all, we really appreciate your project. We'd love to see this feature in upstream greenlight, but this solution might also work very well! :)

Thanks a lot for trying out this software.
Likewise, I would have preferred this functionality in Greenlight itself, but I guess you can't have it all.

> We still struggle to bind ldap anonymously (greenlight ldap-authentication works fine though). Seems like greenlight-ldap-sync is not happy with a zero-length bind DN and/or a zero-length password and keeps returning `invalid DN`.

Honestly, I only tried the simple LDAP authentication with the configured `LDAP_BIND_DN` and `LDAP_PASSWORD` pair, as this was my use case. As not being an LDAP expert, I just took a look at Ruby's Net::LDAP thingy and adjusted the unauthenticated bind within this tool.

I pushed the changes, which I have not tested due to not running an anonymous auth LDAP server, to the new [`ldap-anonymous-bind`](https://github.com/oxzi/greenlight-ldap-sync/tree/ldap-anonymous-bind) branch.
Would you please try out this branch and report back? Thanks!

**Comment by DudeCalledBro** [comment]
Thanks for your quick response and code changes.

The user-string, shows expected values (replaced with "this is fine").

```bash
level=debug msg="Fetched users from SQL" amount=2
level=error msg="Failed to query LDAP user" error="expected exactly one LDAP response, got 0" user="[THIS IS FINE]"
level=error msg="Failed to query LDAP user" error="expected exactly one LDAP response, got 0" user="[THIS IS FINE]"
level=info msg="Finished LDAP sync" fields.time=35.366954ms
```

Thank you again! :)

**Comment by oxzi** [comment]
> Thanks for your quick response and code changes.

You're welcome (:

As the anonymous authentication now seems to work, I merged this testing branch into `master`. Please forget about the other one.

> The user-string, shows expected values (replaced with "this is fine").
> 
> ```shell
> level=debug msg="Fetched users from SQL" amount=2
> level=error msg="Failed to query LDAP user" error="expected exactly one LDAP response, got 0" user="[THIS IS FINE]"
> level=error msg="Failed to query LDAP user" error="expected exactly one LDAP response, got 0" user="[THIS IS FINE]"
> level=info msg="Finished LDAP sync" fields.time=35.366954ms
> ```

Just to be completely sure, the error should occur?
The two users from Greenlight's SQL database, marked with `provider` = `ldap`, are not present in your LDAP?

**Comment by DudeCalledBro** [comment]
> > ```shell
> > level=debug msg="Fetched users from SQL" amount=2
> > level=error msg="Failed to query LDAP user" error="expected exactly one LDAP response, got 0" user="[THIS IS FINE]"
> > level=error msg="Failed to query LDAP user" error="expected exactly one LDAP response, got 0" user="[THIS IS FINE]"
> > level=info msg="Finished LDAP sync" fields.time=35.366954ms
> > ```
> 
> Just to be completely sure, the error should occur?
> The two users from Greenlight's SQL database, marked with `provider` = `ldap`, are not present in your LDAP?

This error should not occur, there is still an issue. Both users are present in LDAP.

**Comment by oxzi** [comment]
> This error should not occur, there is still an issue. Both users are present in LDAP.

Damn.

The LDAP search is based on the following code:
https://github.com/oxzi/greenlight-ldap-sync/blob/da1b34ddddfb19231a62c450196deaa483428ba6/ldap.go#L132-L138

Thus, if you have an `LDAP_FILTER` defined, it might mess something up.
Otherwise, the search is based on `LDAP_UID`, which is `uid` for me.

The requested attributes are mapped internally from Greenlight's intermediate format to a sequence of predefined LDAP or AD attribute names. Please refer to the [`ldapAttrMap` function](https://github.com/oxzi/greenlight-ldap-sync/blob/da1b34ddddfb19231a62c450196deaa483428ba6/ldap.go#L72), where I at least linked the original mapping madness.

Your best help will probably be the log of your LDAP server, I'd guess.
